[package]
name = "tauri-plugin-cache"
version = "0.1.0"
authors = [ "Taiizor" ]
description = ""
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-cache"

[dependencies]
tauri = { version = "2.5.1" }
serde = "1.0"
thiserror = "2"
tauri-plugin-sql = { version = "2.2.0", features = ["sqlite"] }

[build-dependencies]
tauri-plugin = { version = "2.2.0", features = ["build"] }
